### ISSUE TITLE
Error when translating

### ISSUE THREAD

**Issue by YomostXme** [Mabzak-Knight/NyanTranslate#3]
I got this error when translating

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\NyanTranslate\app.py", line 33, in process_data
    bjepang,lines = save_and_translate(img)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\NyanTranslate\penerjemah.py", line 139, in save_and_translate
    kordinat = model2annotation(model_path, img_file, save_dir, save_json=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\NyanTranslate\penerjemah_manga\assets\ctd.py", line 101, in model2annotation
    blk_xyxy = xyxy2yolo(blk_xyxy, im_w, im_h)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program\NyanTranslate\penerjemah_manga\utils\imgproc_utils.py", line 40, in xyxy2yolo
    if xyxy == [] or xyxy == np.array([]) or len(xyxy) == 0:
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (0,) (10,4)

**Comment by Mabzak-Knight** [comment]
Thank you for the information. Regarding this issue, I have already fixed it. You can try checking http://nyantl.ddns.net/# to see if it's still active, or you can run it on Google Colab, which I have tested at https://colab.research.google.com/drive/1VYGrG1XeBse_iUM4QfQHpbL7l0nyzQox?usp=sharing.
