### ISSUE TITLE
error instalasi

### ISSUE THREAD

**Issue by Axel-One** [Mabzak-Knight/NyanTranslate#4]
127.0.0.1 - - [03/Apr/2024 22:30:21] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\flask\app.py", line 1488, in _call_
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PENDUKUNG\NyanTranslate-main\app.py", line 90, in final
    result = subprocess.run(['php', './web/final.php'], capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1026, in _init_
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
127.0.0.1 - - [03/Apr/2024 22:30:22] "GET /?_debugger_=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [03/Apr/2024 22:30:22] "GET /?_debugger_=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [03/Apr/2024 22:30:22] "GET /?_debugger_=yes&cmd=resource&f=console.png HTTP/1.1" 304 -

**Comment by Axel-One** [comment]
entah apa error nya dimana sudah 1 jam saya coba cari masalahnya

**Comment by Axel-One** [comment]
cara make aplikasinya yang benar bagaimana ? apa yang harus dibuka supaya aplikasi berjalan sempurna, punya saya cuma jalan di terminal tidak menampilkan tampilan aplikasi seperti pada gambar

**Comment by Mabzak-Knight** [comment]
klo boleh tau installnya di komputer pribadi atau di tempat lain? bisa juga coba lihat tutorial instalisasi di google colab disini https://www.youtube.com/watch?v=PlbIb--9OMg&ab_channel=RuangIlmuDigital

**Comment by Axel-One** [comment]
pake komputer pribadi

**Comment by Mabzak-Knight** [comment]
klo pakai komputer pribadi kemungkinan ada paket yg belum terinstall atau sudah terinstal tetapi beda versi, ada juga kemungkinan port atau localhost sudah terpakai dengan aplikasi lain, "FileNotFoundError: [WinError 2] The system cannot find the file specified" ini menandakan file webnya tidak ketemu. coba install paket berikut 
``import subprocess``
``apt-get install php``
``from flask import Flask``
pastikan folder2 project tidak ada yg hilang di folder NyanTranslate, jalankan python di dalam foldernya langsung, jika tidak bisa coba gunakan versi google colab disini:
https://colab.research.google.com/drive/1VYGrG1XeBse_iUM4QfQHpbL7l0nyzQox?usp=sharing#scrollTo=q8vCy4JrAcH3

**Comment by Axel-One** [comment]
baik nanti akan saya coba

**Comment by Axel-One** [comment]
bisa jelaskan cara instal paket yang lain gimana ? saya sudah coba tapi beberapa gagal kemungkinan perintahnya tidak sesuai

**Comment by Axel-One** [comment]
tetep gak bisa, apa versi python yang anda pakai untuk membuat ini setidaknya versi yang anda gunakan di vidio tutorial

**Comment by Mabzak-Knight** [comment]
seharusnya versi terbaru bisa, sya pakai komputer tua( core 2 - ddr 3 - ram 4gb - gk pakai vga ) juga masih bisa jalan, klo dari error di stu error saat menjalankan phpnya, jika masih ingin coba2, coba cari tutorial Cara Mengatasi Error 304

**Comment by Axel-One** [comment]
cara buka webnya jika menggunakan komputer pribadi gimana ? saya sudah coba tapi gak mau kebuka padahal errornnya sudah hilang, dan sedikit laporan google colab anda ada error sehingga bahasa mandarin tidak bisa di terjemahkan ke indo dan mungkin hal lain
